# Configuration originally created by Create HTTP Server wizard on Thu May 03 10:47:11 EDT 2012
LoadModule ibm_ssl_module /QSYS.LIB/QHTTPSVR.LIB/QZSRVSSL.SRVPGM
LoadModule deflate_module /QSYS.LIB/QHTTPSVR.LIB/QZSRCORE.SRVPGM
Listen 10.32.234.145:80
Listen 10.32.234.145:443

SetEnv LLPROGRAM SEWEBTP/LLSEWEBTWB
SetEnv IFSPath /EWEBT/templates
SetEnv CookieName SEWEBTCOM
SetEnv Company 01
SetEnv URLOverrideNew 10.32.234.145
SetEnv REFERERMATCH01 10.32.234.145
SetEnv REFERERMATCH02 10.32.234.145
SetEnv REFERERMATCH03
SetEnv REFERERMATCH04
SetEnv SUPPORTSSSL N

AddOutputFilterByType DEFLATE text/css application/x-javascript application/javascript text/html

Options -ExecCGI -Includes -IncludesNoExec -Indexes -MultiViews
LimitRequestBody 104857600
TimeOut 400
CGIConvMode %%EBCDIC/MIXED%%
MaxCGIJobs 100
DirectoryIndex index.html welcome.html index.html

SSLCacheEnable

# Serve Angular's index.html for any URL that doesn't match a real file
ErrorDocument 404 /index.html

LogFormat "%h %T %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%{Cookie}n \"%r\" %t" cookie
LogFormat "%{User-agent}i" agent
LogFormat "%{Referer}i -> %U" referer
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog logs/access_log combined
LogMaint logs/access_log 2 0
LogMaint logs/error_log 2 0
DocumentRoot /SEWEBT
AccessFileName .htaccess


<Directory />
    Order Allow,Deny
    Deny From all
    UserID %%SERVER%%
</Directory>

<Directory /www/SEWEBT/htdocs>
    Order Allow,Deny
    Allow From all
</Directory>

<Directory /SEWEBT/root>
    Order Allow,Deny
    Allow From all
</Directory>

<Directory /photos/styles>
    Order Allow,Deny
    Allow From all
</Directory>

<Directory /photos>
    Order Allow,Deny
    Allow From all
</Directory>

<Directory /QSYS.LIB/SEWEBTP.LIB>
    Options +ExecCGI
    Allow From all
</Directory>

MapMatch ^/cgi/(.*) /QSYS.LIB/SEWEBTP.LIB/$1.PGM
ScriptAliasMatch ^/QSYS\.LIB/SEWEBTP\.LIB/(.*) /QSYS.LIB/SEWEBTP.LIB/$1
AliasMatch ^/photos/styles/(.*) /photos/styles/$1
AliasMatch ^/photos/(.*) /photos/$1
AliasMatch ^/(.*) /SEWEBT/root/$1
