export interface TpSettings {
  tp_id:         number;
  cont_name:     string | null;
  pric_eml:      string | null;
  pric_phn:      string | null;
  adm_ct_eml:    string | null;
  adm_ct_phn:    string | null;
  supprt_name:   string | null;
  supprt_eml:    string | null;
  comp_name:     string | null;
  dflt_lang:     string;
  bilng_mode:    'Y' | 'N';
  timezone:      string;
  currency:      string;
  fisc_yr_mo:    number;
  addr_line1:    string | null;
  addr_line2:    string | null;
  city:          string | null;
  province:      string | null;
  postal_code:   string | null;
  country:       string;
  meas_sys:      'METRIC' | 'IMPERIAL' | null;
  mfa_reqd:      'Y' | 'N';
  ses_timeout:   number | null;
  data_resid:    string | null;
  logo_url:      string | null;
  sup_logo_url:  string | null;
  login_img:     string | null;
  hero_img:      string | null;
  men_clth_im:   string | null;
  men_ftw_im:    string | null;
  men_gear_im:   string | null;
  instag_url:    string | null;
  facebk_url:    string | null;
  youtub_url:    string | null;
  linkdin_url:   string | null;
  twiter_url:    string | null;
  shopng_url:    string | null;
  welcom_copy:   string | null;
  alert_copy:    string | null;
  hero_copy:     string | null;
  shop_copy:     string | null;
  botm_copy:     string | null;
  copyrg_txt:    string | null;
  privcyinfo:    string | null;
  privcyinfo1:   string | null;
  privcyinfo2:   string | null;
  privcyinfo3:   string | null;
  privcyinfo4:   string | null;
  privcyinfo5:   string | null;
  privcyinfo6:   string | null;
  privcyinfo7:   string | null;
  termsinfo:     string | null;
  termsinfo1:    string | null;
  termsinfo2:    string | null;
  termsinfo3:    string | null;
  termsinfo4:    string | null;
  termsinfo5:    string | null;
  termsinfo6:    string | null;
  termsinfo7:    string | null;
  retnsinfo:     string | null;
  retnsinfo1:    string | null;
  retnsinfo2:    string | null;
  retnsinfo3:    string | null;
  retnsinfo4:    string | null;
  retnsinfo5:    string | null;
  retnsinfo6:    string | null;
  retnsinfo7:    string | null;
  idpcfgjsn:     string | null;
  updated_by:    string | null;
  created_ts:    string;
  updated_ts:    string;
}
